[package]
name = "soa_iter_bench"
version = "0.1.0"
authors = ["Your Name <>"]

[dependencies]
lazy_static = "*"
rand = "*"
itertools = "*"
soa_derive = { git = "https://github.com/lumol-org/soa-derive" }

